thm_base="$base"
thm_surface="$surface"
thm_overlay="$overlay"
thm_muted="$muted"
thm_subtle="$subtle"
thm_text="$text"
thm_crimson="$crimson"
thm_sun="$sun"
thm_amber="$amber"
thm_moss="$moss"
thm_leaf="$leaf"
thm_haze="$haze"
thm_highlight_low="$highlightLow"
thm_highlight_med="$highlightMed"
thm_highlight_high="$highlightHigh"

